"""
Purchase order documents, generated after a person approves.

A purchase order is a commitment, so the one rule this file exists to enforce is
in the first few lines of `build`: an unapproved recommendation produces nothing.
The system never places an order and never sends anything anywhere -- it hands
a buyer a document, and issuing it stays a human act. Every page says so.

One PO per supplier, because that is what a purchase order is. A plan that
spans three suppliers is three orders with three numbers, three delivery dates
and three sets of terms; printing them as one document would be a thing no
buyer could actually send.

The numbering is derived, not sequential: PO-<reco id>-<supplier code>. Two runs
of the same approved recommendation produce the same numbers rather than
consuming a counter, which matters when the thing is regenerated on stage.
"""

from __future__ import annotations

import io
import zipfile
from datetime import date
from typing import Dict, List

from fpdf import FPDF
from fpdf.enums import XPos, YPos

BUYER = "Kestrel Electronics Pvt Ltd"
BUYER_SITE = "Plant 2, Hosur, Tamil Nadu 635109, India"
BUYER_GST = "33AABCK1234M1Z5"

INK = (32, 38, 48)
MUTED = (122, 132, 148)
RULE = (176, 184, 196)
HEAD_FILL = (232, 236, 242)

TERMS = [
    "1. Prices are as quoted at the time of this order and include no taxes or duties "
    "unless stated.",
    "2. Delivery to the buyer's plant address above. Partial shipment is not accepted "
    "without written agreement.",
    "3. Parts must be supplied with a certificate of conformance and full lot "
    "traceability.",
    "4. Date codes older than 24 months at receipt may be rejected.",
    "5. Moisture-sensitive devices must ship in sealed dry packaging per J-STD-033.",
    "6. This order is issued subject to the buyer's standard purchasing terms.",
]


class NotApproved(RuntimeError):
    pass


def _load(conn, reco_id: int) -> Dict:
    with conn.cursor() as cur:
        cur.execute("""SELECT r.id, r.status, r.approved_by, r.approved_at,
                              r.need_by, r.strategy, c.mpn
                         FROM platform.purchase_recommendations r
                         JOIN erp.components c ON c.id = r.original_component_id
                        WHERE r.id = %s""", (reco_id,))
        head = cur.fetchone()
        if head is None:
            raise NotApproved(f"No recommendation {reco_id}.")

        cur.execute("""SELECT s.code, s.name, s.country, s.city,
                              c.mpn, c.manufacturer, c.description,
                              l.quantity, l.unit_price, l.line_total,
                              l.lead_time_days, l.expected_arrival
                         FROM platform.purchase_recommendation_lines l
                         JOIN erp.suppliers s  ON s.id = l.supplier_id
                         JOIN erp.components c ON c.id = l.component_id
                        WHERE l.recommendation_id = %s
                        ORDER BY s.name""", (reco_id,))
        cols = [d[0] for d in cur.description]
        lines = [dict(zip(cols, row)) for row in cur.fetchall()]

    return {
        "id": head[0], "status": head[1], "approved_by": head[2],
        "approved_at": head[3], "need_by": head[4], "strategy": head[5],
        "original_mpn": head[6], "lines": lines,
    }


class Sheet(FPDF):
    def footer(self) -> None:
        self.set_y(-14)
        self.set_draw_color(*RULE)
        self.set_line_width(0.2)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(1)
        self.set_font("Helvetica", "", 6.5)
        self.set_text_color(*MUTED)
        self.cell(0, 4,
                  "Generated by Overlay from an approved recommendation. "
                  "Not transmitted to the supplier: issuing this order is a human act.",
                  align="C")


def _page(pdf: Sheet, reco: Dict, supplier_code: str, rows: List[Dict]) -> None:
    first = rows[0]
    po_number = f"PO-{reco['id']}-{supplier_code}"
    latest = max(r["expected_arrival"] for r in rows)
    total = sum(float(r["line_total"]) for r in rows)

    pdf.add_page()
    pdf.set_text_color(*INK)

    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(110, 7, "PURCHASE ORDER", new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, po_number, align="R", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_draw_color(*RULE)
    pdf.set_line_width(0.5)
    y = pdf.get_y() + 1
    pdf.line(pdf.l_margin, y, pdf.w - pdf.r_margin, y)
    pdf.ln(4)

    # buyer / supplier blocks
    left, right = 92, 92
    pdf.set_font("Helvetica", "", 6.5)
    pdf.set_text_color(*MUTED)
    pdf.cell(left, 4, "  BUYER", new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(right, 4, "  SUPPLIER", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*INK)
    supplier_where = ", ".join(x for x in [first.get("city"), first["country"]] if x)
    buyer_block = f"{BUYER}\n{BUYER_SITE}\nGSTIN {BUYER_GST}"
    supp_block = f"{first['name']}\n{supplier_where}\nSupplier code {supplier_code}"
    top = pdf.get_y()
    pdf.multi_cell(left, 4.4, buyer_block, border=1)
    bottom_left = pdf.get_y()
    pdf.set_xy(pdf.l_margin + left, top)
    pdf.multi_cell(right, 4.4, supp_block, border=1)
    pdf.set_y(max(bottom_left, pdf.get_y()))
    pdf.ln(3)

    # order facts
    facts = [("Order date", str(date.today())), ("Required by", str(reco["need_by"])),
             ("Promised", str(latest)), ("Currency", "USD"),
             ("Approved by", reco["approved_by"] or "-")]
    pdf.set_font("Helvetica", "", 6.5)
    pdf.set_text_color(*MUTED)
    for name, _ in facts:
        pdf.cell(36.8, 3.8, "  " + name.upper(), new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.ln(3.8)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(*INK)
    for _, value in facts:
        pdf.cell(36.8, 5, "  " + value, border=1, new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.ln(7)

    # lines
    cols = [("Item", 10), ("Manufacturer P/N", 40), ("Manufacturer", 32),
            ("Description", 46), ("Qty", 14), ("Unit", 18), ("Amount", 24)]
    pdf.set_font("Courier", "B", 7)
    pdf.set_fill_color(*HEAD_FILL)
    for name, w in cols:
        pdf.cell(w, 5, " " + name, border=1, fill=True, new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.ln(5)

    pdf.set_font("Courier", "", 7)
    for i, row in enumerate(rows, start=1):
        cells = [str(i), row["mpn"], row["manufacturer"][:20],
                 (row["description"] or "")[:30], f"{row['quantity']:,}",
                 f"{float(row['unit_price']):.4f}", f"{float(row['line_total']):,.2f}"]
        for (_, w), text in zip(cols, cells):
            pdf.cell(w, 4.8, " " + text, border=1, new_x=XPos.RIGHT, new_y=YPos.TOP)
        pdf.ln(4.8)

    pdf.set_font("Courier", "B", 8)
    pdf.cell(sum(w for _, w in cols[:-1]), 5.4, "ORDER TOTAL (USD)  ", align="R",
             new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(cols[-1][1], 5.4, f" {total:,.2f}", border=1, fill=True,
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(5)

    pdf.set_font("Helvetica", "", 7)
    pdf.set_text_color(*MUTED)
    pdf.multi_cell(0, 3.7,
                   f"Raised against recommendation #{reco['id']} ({reco['strategy']}), "
                   f"replacing {reco['original_mpn']}. Approved by "
                   f"{reco['approved_by'] or '-'}"
                   + (f" on {reco['approved_at']:%Y-%m-%d}" if reco["approved_at"] else "")
                   + ".",
                   new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(*INK)
    pdf.cell(0, 5, "Terms", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 7)
    pdf.set_text_color(*MUTED)
    for term in TERMS:
        pdf.multi_cell(0, 3.7, term, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.ln(6)
    pdf.set_text_color(*INK)
    pdf.set_font("Helvetica", "", 8)
    pdf.cell(90, 12, "  Authorised signature", border=1,
             new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(0, 12, "  Date", border=1, new_x=XPos.LMARGIN, new_y=YPos.NEXT)


def _approved(conn, reco_id: int) -> Dict:
    """The recommendation, or a refusal. Every path into a PO comes through here."""
    reco = _load(conn, reco_id)
    if reco["status"] != "APPROVED":
        raise NotApproved(
            f"Recommendation {reco_id} is {reco['status'].replace('_', ' ').lower()}. "
            f"A purchase order is only produced once a person has approved the plan."
        )
    if not reco["lines"]:
        raise NotApproved(f"Recommendation {reco_id} has no supplier lines.")
    return reco


def _grouped(reco: Dict) -> Dict[str, List[Dict]]:
    by_supplier: Dict[str, List[Dict]] = {}
    for row in reco["lines"]:
        by_supplier.setdefault(row["code"], []).append(row)
    return by_supplier


def _render(reco: Dict, groups: Dict[str, List[Dict]]) -> bytes:
    pdf = Sheet(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=18)
    for code, rows in groups.items():
        _page(pdf, reco, code, rows)
    out = pdf.output()
    return bytes(out) if not isinstance(out, (bytes, bytearray)) else bytes(out)


def build(conn, reco_id: int, supplier_code: str = None) -> bytes:
    """
    Purchase orders for an approved recommendation.

    With `supplier_code`, one order for one supplier -- the file that is actually
    sent. Without, every order in one document, which is the internal review
    copy and must not leave the building: page two carries a second supplier's
    quantities and unit prices, and page three a third's. Handing that to any
    one of them shows what the others quoted.
    """
    reco = _approved(conn, reco_id)
    groups = _grouped(reco)

    if supplier_code:
        rows = groups.get(supplier_code)
        if not rows:
            raise NotApproved(
                f"Recommendation {reco_id} has no line for supplier "
                f"{supplier_code}.")
        groups = {supplier_code: rows}

    return _render(reco, groups)


def build_zip(conn, reco_id: int) -> bytes:
    """
    One PDF per supplier, zipped -- the set a buyer sends out.

    Separate files rather than separate pages, because each one goes to a
    different company and must contain nothing about the others.
    """
    reco = _approved(conn, reco_id)
    buffer = io.BytesIO()

    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        for code, rows in _grouped(reco).items():
            archive.writestr(f"PO-{reco_id}-{code}.pdf",
                             _render(reco, {code: rows}))
    return buffer.getvalue()


def summary(conn, reco_id: int) -> Dict:
    """What the interface needs to list the documents without building them."""
    reco = _load(conn, reco_id)
    orders = []
    for code, rows in _grouped(reco).items():
        orders.append({
            "po_number": f"PO-{reco['id']}-{code}",
            "supplier_code": code,
            "supplier": rows[0]["name"],
            "country": rows[0]["country"],
            "quantity": sum(int(r["quantity"]) for r in rows),
            "total": round(sum(float(r["line_total"]) for r in rows), 2),
            "promised": str(max(r["expected_arrival"] for r in rows)),
        })
    orders.sort(key=lambda o: o["supplier"])
    return {
        "recommendation_id": reco["id"],
        "status": reco["status"],
        "approved_by": reco["approved_by"],
        "orders": orders,
    }
