-- ============================================================================
--  Master / reference data for the dummy ERP.
--
--  IMPORTANT -- everything in this file is FABRICATED DEMO DATA.
--  Real distributor names (DigiKey, Mouser, Arrow, Avnet, Rutronik) are used
--  only as realistic labels; every price, stock figure and lead time here is
--  invented. The suppliers that the demo disruption story touches are entirely
--  fictional companies on purpose -- we never attach a made-up trade-restriction
--  narrative to a real named company.
--
--  Hand-written rows live here because the demo depends on their exact values.
--  Bulk/noise rows are generated by seed_orders.py.
-- ============================================================================

-- ---------------------------------------------------------------- warehouses
INSERT INTO erp.warehouses (id, code, name, country) VALUES
  (1, 'WH-CHN', 'Chennai Plant Store',      'India'),
  (2, 'WH-PEN', 'Penang Distribution Hub',  'Malaysia'),
  (3, 'WH-GDL', 'Guadalajara Plant Store',  'Mexico');

-- ------------------------------------------------------------------ products
INSERT INTO erp.products (id, sku, name, family, description) VALUES
  (1, 'MC-3000', 'Motor Controller Board MC-3000',  'Industrial Drives', 'Three-phase BLDC motor controller, 48V / 30A, CAN + USB service port'),
  (2, 'IG-500',  'Industrial IoT Gateway IG-500',   'Connectivity',      'Wi-Fi + Ethernet edge gateway for factory telemetry'),
  (3, 'PI-750',  'Power Inverter Module PI-750',    'Power',             '750W DC-AC inverter module with CAN supervision'),
  (4, 'SD-220',  'Servo Drive Board SD-220',        'Industrial Drives', '220W servo drive, closed-loop position control');

-- ---------------------------------------------------------------- components
-- specs keys are NORMALISED on purpose: the compatibility checker reads these
-- exact fields. footprint_id and pinout_family are the hard gates.
INSERT INTO erp.components (id, mpn, manufacturer, category, description, lifecycle, standard_cost, country_of_origin, specs) VALUES
  (1, 'STM32F407VGT6', 'STMicroelectronics', 'MCU', 'Cortex-M4F MCU, 168 MHz, 1 MB flash, LQFP-100', 'ACTIVE', 9.4000, 'France',
   '{"footprint_id":"LQFP100_14X14_P050","package":"LQFP-100","pin_count":100,"pitch_mm":0.5,"body_mm":"14x14","pinout_family":"STM32F4_V100","core":"ARM Cortex-M4F","max_freq_mhz":168,"flash_kb":1024,"ram_kb":192,"vcc_min_v":1.8,"vcc_max_v":3.6,"io_count":82,"adc_channels":16,"temp_min_c":-40,"temp_max_c":85,"interfaces":["USART","SPI","I2C","CAN","USB_OTG_FS","SDIO","ADC12"],"rohs":true}'),
  (2, 'STM32F429VGT6', 'STMicroelectronics', 'MCU', 'Cortex-M4F MCU, 180 MHz, 1 MB flash, 256 KB RAM, LQFP-100', 'ACTIVE', 10.8500, 'France',
   '{"footprint_id":"LQFP100_14X14_P050","package":"LQFP-100","pin_count":100,"pitch_mm":0.5,"body_mm":"14x14","pinout_family":"STM32F4_V100","core":"ARM Cortex-M4F","max_freq_mhz":180,"flash_kb":1024,"ram_kb":256,"vcc_min_v":1.8,"vcc_max_v":3.6,"io_count":82,"adc_channels":16,"temp_min_c":-40,"temp_max_c":85,"interfaces":["USART","SPI","I2C","CAN","USB_OTG_FS","SDIO","ADC12"],"rohs":true}'),
  (3, 'STM32F429ZIT6', 'STMicroelectronics', 'MCU', 'Cortex-M4F MCU, 180 MHz, 2 MB flash, LQFP-144', 'ACTIVE', 12.7000, 'France',
   '{"footprint_id":"LQFP144_20X20_P050","package":"LQFP-144","pin_count":144,"pitch_mm":0.5,"body_mm":"20x20","pinout_family":"STM32F4_Z144","core":"ARM Cortex-M4F","max_freq_mhz":180,"flash_kb":2048,"ram_kb":256,"vcc_min_v":1.8,"vcc_max_v":3.6,"io_count":114,"adc_channels":24,"temp_min_c":-40,"temp_max_c":85,"interfaces":["USART","SPI","I2C","CAN","USB_OTG_FS","SDIO","ADC12"],"rohs":true}'),
  (4, 'STM32F405RGT6', 'STMicroelectronics', 'MCU', 'Cortex-M4F MCU, 168 MHz, 1 MB flash, LQFP-64', 'ACTIVE', 9.3000, 'France',
   '{"footprint_id":"LQFP64_10X10_P050","package":"LQFP-64","pin_count":64,"pitch_mm":0.5,"body_mm":"10x10","pinout_family":"STM32F4_R64","core":"ARM Cortex-M4F","max_freq_mhz":168,"flash_kb":1024,"ram_kb":192,"vcc_min_v":1.8,"vcc_max_v":3.6,"io_count":51,"adc_channels":16,"temp_min_c":-40,"temp_max_c":85,"interfaces":["USART","SPI","I2C","CAN","USB_OTG_FS","SDIO","ADC12"],"rohs":true}'),
  (5, 'GD32F407VGT6', 'GigaDevice', 'MCU', 'Cortex-M4 MCU, 168 MHz, 1 MB flash, LQFP-100, pin-compatible with STM32F407V', 'ACTIVE', 5.9500, 'China',
   '{"footprint_id":"LQFP100_14X14_P050","package":"LQFP-100","pin_count":100,"pitch_mm":0.5,"body_mm":"14x14","pinout_family":"STM32F4_V100","core":"ARM Cortex-M4","max_freq_mhz":168,"flash_kb":1024,"ram_kb":192,"vcc_min_v":2.6,"vcc_max_v":3.6,"io_count":82,"adc_channels":16,"temp_min_c":-40,"temp_max_c":85,"interfaces":["USART","SPI","I2C","CAN","USB_OTG_FS","SDIO","ADC12"],"rohs":true}'),
  (6, 'STM32F407VGT7', 'STMicroelectronics', 'MCU', 'Cortex-M4F MCU, 168 MHz, 1 MB flash, LQFP-100, industrial temp grade', 'ACTIVE', 13.4000, 'France',
   '{"footprint_id":"LQFP100_14X14_P050","package":"LQFP-100","pin_count":100,"pitch_mm":0.5,"body_mm":"14x14","pinout_family":"STM32F4_V100","core":"ARM Cortex-M4F","max_freq_mhz":168,"flash_kb":1024,"ram_kb":192,"vcc_min_v":1.8,"vcc_max_v":3.6,"io_count":82,"adc_channels":16,"temp_min_c":-40,"temp_max_c":105,"interfaces":["USART","SPI","I2C","CAN","USB_OTG_FS","SDIO","ADC12"],"rohs":true}'),
  (7, 'DRV8301DCAR', 'Texas Instruments', 'GATE_DRIVER', 'Three-phase gate driver with buck and current shunt amps, HTSSOP-56', 'ACTIVE', 4.8500, 'United States',
   '{"footprint_id":"HTSSOP56_PWP","package":"HTSSOP-56","pin_count":56,"vcc_min_v":6.0,"vcc_max_v":60.0,"temp_min_c":-40,"temp_max_c":125,"phases":3,"rohs":true}'),
  (8, 'IRFB4110PBF', 'Infineon', 'MOSFET', 'N-channel MOSFET 100 V 180 A, TO-220AB', 'ACTIVE', 2.3500, 'Germany',
   '{"footprint_id":"TO220AB_3L","package":"TO-220AB","pin_count":3,"vds_v":100,"id_a":180,"rds_on_mohm":4.5,"temp_min_c":-55,"temp_max_c":175,"rohs":true}'),
  (9, 'TPS54331DDAR', 'Texas Instruments', 'REGULATOR_BUCK', '3 A step-down converter, 3.5-28 V input, SOIC-8 PowerPAD', 'ACTIVE', 0.9200, 'United States',
   '{"footprint_id":"SOIC8_PWPAD","package":"SOIC-8 PowerPAD","pin_count":8,"vin_min_v":3.5,"vin_max_v":28.0,"iout_a":3.0,"temp_min_c":-40,"temp_max_c":125,"rohs":true}'),
  (10, 'AMS1117-3.3', 'Advanced Monolithic Systems', 'REGULATOR_LDO', '1 A LDO, fixed 3.3 V, SOT-223', 'ACTIVE', 0.1400, 'China',
   '{"footprint_id":"SOT223_4L","package":"SOT-223","pin_count":4,"vout_v":3.3,"iout_a":1.0,"dropout_v":1.3,"temp_min_c":-40,"temp_max_c":125,"rohs":true}'),
  (11, 'SN65HVD230DR', 'Texas Instruments', 'CAN_TRANSCEIVER', '3.3 V CAN transceiver, 1 Mbps, SOIC-8', 'ACTIVE', 1.0500, 'United States',
   '{"footprint_id":"SOIC8_150MIL","package":"SOIC-8","pin_count":8,"vcc_min_v":3.0,"vcc_max_v":3.6,"data_rate_mbps":1.0,"temp_min_c":-40,"temp_max_c":85,"rohs":true}'),
  (12, 'TCAN332DR', 'Texas Instruments', 'CAN_TRANSCEIVER', '3.3 V CAN transceiver, 1 Mbps, SOIC-8', 'ACTIVE', 1.3500, 'United States',
   '{"footprint_id":"SOIC8_150MIL","package":"SOIC-8","pin_count":8,"vcc_min_v":3.0,"vcc_max_v":3.6,"data_rate_mbps":1.0,"temp_min_c":-40,"temp_max_c":125,"rohs":true}'),
  (13, 'MCP2551-I/SN', 'Microchip', 'CAN_TRANSCEIVER', '5 V CAN transceiver, 1 Mbps, SOIC-8', 'ACTIVE', 0.9500, 'Thailand',
   '{"footprint_id":"SOIC8_150MIL","package":"SOIC-8","pin_count":8,"vcc_min_v":4.5,"vcc_max_v":5.5,"data_rate_mbps":1.0,"temp_min_c":-40,"temp_max_c":85,"rohs":true}'),
  (14, 'W25Q128JVSIQ', 'Winbond', 'FLASH_SPI', '128 Mbit SPI NOR flash, SOIC-8 208 mil', 'ACTIVE', 1.8500, 'Taiwan',
   '{"footprint_id":"SOIC8_208MIL","package":"SOIC-8 208mil","pin_count":8,"density_mbit":128,"vcc_min_v":2.7,"vcc_max_v":3.6,"interface":"SPI","temp_min_c":-40,"temp_max_c":85,"rohs":true}'),
  (15, 'MX25L12835FM2I-10G', 'Macronix', 'FLASH_SPI', '128 Mbit SPI NOR flash, SOIC-8 208 mil', 'ACTIVE', 1.7200, 'Taiwan',
   '{"footprint_id":"SOIC8_208MIL","package":"SOIC-8 208mil","pin_count":8,"density_mbit":128,"vcc_min_v":2.7,"vcc_max_v":3.6,"interface":"SPI","temp_min_c":-40,"temp_max_c":85,"rohs":true}'),
  (16, 'ESP32-WROOM-32E-N8', 'Espressif', 'MODULE_WIFI', 'Wi-Fi + BT module, 8 MB flash, SMD castellated', 'ACTIVE', 3.1000, 'China',
   '{"footprint_id":"ESP32_WROOM_38P","package":"SMD Module","pin_count":38,"vcc_min_v":3.0,"vcc_max_v":3.6,"temp_min_c":-40,"temp_max_c":85,"interfaces":["WIFI","BLE","UART","SPI","I2C"],"rohs":true}'),
  (17, 'LAN8720AI-CP-TR', 'Microchip', 'ETHERNET_PHY', '10/100 Ethernet PHY with RMII, QFN-24 4x4', 'ACTIVE', 1.9500, 'Thailand',
   '{"footprint_id":"QFN24_4X4_P050","package":"QFN-24","pin_count":24,"vcc_min_v":3.0,"vcc_max_v":3.6,"interface":"RMII","temp_min_c":-40,"temp_max_c":85,"rohs":true}'),
  (18, 'KSZ8081RNBIA-TR', 'Microchip', 'ETHERNET_PHY', '10/100 Ethernet PHY with RMII, QFN-32 5x5', 'ACTIVE', 2.2500, 'Thailand',
   '{"footprint_id":"QFN32_5X5_P050","package":"QFN-32","pin_count":32,"vcc_min_v":3.0,"vcc_max_v":3.6,"interface":"RMII","temp_min_c":-40,"temp_max_c":85,"rohs":true}'),
  (19, 'ABM8-25.000MHZ-D2Y-T', 'Abracon', 'CRYSTAL', '25 MHz crystal, 18 pF, 20 ppm, SMD 3225', 'ACTIVE', 0.3800, 'Taiwan',
   '{"footprint_id":"SMD3225_4P","package":"SMD-3225","pin_count":4,"freq_mhz":25.0,"load_cap_pf":18,"tolerance_ppm":20,"temp_min_c":-20,"temp_max_c":70,"rohs":true}'),
  (20, 'USBLC6-2SC6', 'STMicroelectronics', 'ESD_PROTECTION', 'Dual-line USB ESD protection, SOT-23-6', 'ACTIVE', 0.2200, 'France',
   '{"footprint_id":"SOT23_6L","package":"SOT-23-6","pin_count":6,"vrwm_v":5.25,"temp_min_c":-40,"temp_max_c":125,"rohs":true}'),
  (21, 'GRM188R71H104KA93D', 'Murata', 'CAPACITOR_MLCC', '100 nF 50 V X7R 10% 0603', 'ACTIVE', 0.0110, 'Japan',
   '{"footprint_id":"C_0603","package":"0603","capacitance_nf":100,"voltage_v":50,"dielectric":"X7R","tolerance_pct":10,"temp_min_c":-55,"temp_max_c":125,"rohs":true}'),
  (22, 'CL10B104KB8NNNC', 'Samsung Electro-Mechanics', 'CAPACITOR_MLCC', '100 nF 50 V X7R 10% 0603', 'ACTIVE', 0.0080, 'South Korea',
   '{"footprint_id":"C_0603","package":"0603","capacitance_nf":100,"voltage_v":50,"dielectric":"X7R","tolerance_pct":10,"temp_min_c":-55,"temp_max_c":125,"rohs":true}'),
  (23, 'GRM21BR61E106KA73L', 'Murata', 'CAPACITOR_MLCC', '10 uF 25 V X5R 10% 0805', 'ACTIVE', 0.0480, 'Japan',
   '{"footprint_id":"C_0805","package":"0805","capacitance_nf":10000,"voltage_v":25,"dielectric":"X5R","tolerance_pct":10,"temp_min_c":-55,"temp_max_c":85,"rohs":true}'),
  (24, 'RC0603FR-0710KL', 'Yageo', 'RESISTOR', '10 kohm 1% 0.1 W 0603', 'ACTIVE', 0.0040, 'Taiwan',
   '{"footprint_id":"R_0603","package":"0603","resistance_ohm":10000,"tolerance_pct":1,"power_w":0.1,"temp_min_c":-55,"temp_max_c":155,"rohs":true}'),
  (25, 'RC0603FR-07100RL', 'Yageo', 'RESISTOR', '100 ohm 1% 0.1 W 0603', 'ACTIVE', 0.0040, 'Taiwan',
   '{"footprint_id":"R_0603","package":"0603","resistance_ohm":100,"tolerance_pct":1,"power_w":0.1,"temp_min_c":-55,"temp_max_c":155,"rohs":true}'),
  (26, 'SRN6045TA-100M', 'Bourns', 'INDUCTOR', '10 uH 3.0 A shielded power inductor, 6.0x4.5 mm', 'ACTIVE', 0.2900, 'Taiwan',
   '{"footprint_id":"L_6045","package":"SMD-6045","inductance_uh":10,"current_a":3.0,"tolerance_pct":20,"temp_min_c":-40,"temp_max_c":125,"rohs":true}'),
  (27, '43045-0400', 'Molex', 'CONNECTOR', 'Micro-Fit 3.0 header, 4 position, right angle', 'ACTIVE', 0.6200, 'United States',
   '{"footprint_id":"MOLEX_43045_4P","package":"Header","pin_count":4,"pitch_mm":3.0,"current_a":8.5,"temp_min_c":-40,"temp_max_c":105,"rohs":true}'),
  (28, 'SMAJ33A', 'Littelfuse', 'TVS_DIODE', '400 W TVS diode, 33 V unidirectional, DO-214AC', 'ACTIVE', 0.1900, 'Philippines',
   '{"footprint_id":"DO214AC_SMA","package":"DO-214AC","pin_count":2,"vrwm_v":33,"power_w":400,"temp_min_c":-55,"temp_max_c":150,"rohs":true}'),
  (29, 'NCP1117ST33T3G', 'onsemi', 'REGULATOR_LDO', '1 A LDO, fixed 3.3 V, SOT-223', 'ACTIVE', 0.3100, 'Czech Republic',
   '{"footprint_id":"SOT223_4L","package":"SOT-223","pin_count":4,"vout_v":3.3,"iout_a":1.0,"dropout_v":1.2,"temp_min_c":-40,"temp_max_c":125,"rohs":true}'),
  (30, 'RC0603FR-074K7L', 'Yageo', 'RESISTOR', '4.7 kohm 1% 0.1 W 0603', 'ACTIVE', 0.0040, 'Taiwan',
   '{"footprint_id":"R_0603","package":"0603","resistance_ohm":4700,"tolerance_pct":1,"power_w":0.1,"temp_min_c":-55,"temp_max_c":155,"rohs":true}');

-- ----------------------------------------------------------------- suppliers
INSERT INTO erp.suppliers (id, code, name, supplier_type, country, region, city, reliability_score, avg_lead_time_days) VALUES
  (1,  'SUP-001', 'Shenzhen Ruiyang Semiconductor Co. Ltd',       'DISTRIBUTOR',  'China',          'APAC',   'Shenzhen',          0.880, 21),
  (2,  'SUP-002', 'TaiChip Components Ltd',                        'DISTRIBUTOR',  'Taiwan',         'APAC',   'Kaohsiung',         0.930, 18),
  (3,  'SUP-003', 'Nexperia Europe B.V.',                          'MANUFACTURER', 'Netherlands',    'EMEA',   'Nijmegen',          0.960, 20),
  (4,  'SUP-004', 'DigiKey Electronics',                           'DISTRIBUTOR',  'United States',  'AMER',   'Thief River Falls', 0.990,  7),
  (5,  'SUP-005', 'Mouser Electronics',                            'DISTRIBUTOR',  'United States',  'AMER',   'Mansfield',         0.980, 10),
  (6,  'SUP-006', 'Arrow Electronics',                             'DISTRIBUTOR',  'United States',  'AMER',   'Centennial',        0.970,  5),
  (7,  'SUP-007', 'Avnet Asia Pte Ltd',                            'DISTRIBUTOR',  'Singapore',      'APAC',   'Singapore',         0.950, 12),
  (8,  'SUP-008', 'Fujian Longtai Electronics Co. Ltd',            'MANUFACTURER', 'China',          'APAC',   'Xiamen',            0.840, 25),
  (9,  'SUP-009', 'Hanwoo Precision Co. Ltd',                      'MANUFACTURER', 'South Korea',    'APAC',   'Cheonan',           0.940, 16),
  (10, 'SUP-010', 'Rutronik Elektronische Bauelemente GmbH',       'DISTRIBUTOR',  'Germany',        'EMEA',   'Ispringen',         0.960,  9);

-- ----------------------------------------------------------------------- BOM
-- MC-3000 (product 1)
INSERT INTO erp.bom (product_id, component_id, qty_per_unit, reference_designators, is_critical, design_constraints) VALUES
  (1,  1,  1, 'U1',                          TRUE,
   '{"footprint_id":"LQFP100_14X14_P050","pinout_family":"STM32F4_V100","rail_voltage_v":3.3,"ambient_temp_min_c":-20,"ambient_temp_max_c":85,"min_flash_kb":1024,"min_ram_kb":160,"min_io_count":78,"min_freq_mhz":160,"min_adc_channels":16,"required_interfaces":["USART","SPI","I2C","CAN","USB_OTG_FS","ADC12"]}'),
  (1,  7,  1, 'U2',                          TRUE,
   '{"footprint_id":"HTSSOP56_PWP","ambient_temp_min_c":-20,"ambient_temp_max_c":85}'),
  (1,  8,  6, 'Q1-Q6',                       TRUE,  '{"footprint_id":"TO220AB_3L","min_vds_v":80,"min_id_a":120}'),
  (1,  9,  1, 'U3',                          FALSE, '{"footprint_id":"SOIC8_PWPAD"}'),
  (1, 10,  1, 'U4',                          FALSE, '{"footprint_id":"SOT223_4L","vout_v":3.3,"min_iout_a":0.8}'),
  (1, 11,  1, 'U5',                          TRUE,
   '{"footprint_id":"SOIC8_150MIL","rail_voltage_v":3.3,"ambient_temp_min_c":-20,"ambient_temp_max_c":85,"min_data_rate_mbps":1.0}'),
  (1, 14,  1, 'U6',                          FALSE, '{"footprint_id":"SOIC8_208MIL","min_density_mbit":128,"rail_voltage_v":3.3}'),
  (1, 19,  1, 'Y1',                          FALSE, '{"footprint_id":"SMD3225_4P","freq_mhz":25.0}'),
  (1, 20,  1, 'D1',                          FALSE, '{"footprint_id":"SOT23_6L"}'),
  (1, 21, 28, 'C1-C28',                      FALSE, '{"footprint_id":"C_0603","capacitance_nf":100,"min_voltage_v":50,"dielectric":"X7R"}'),
  (1, 23,  8, 'C29-C36',                     FALSE, '{"footprint_id":"C_0805","capacitance_nf":10000,"min_voltage_v":25}'),
  (1, 24, 14, 'R1-R14',                      FALSE, '{"footprint_id":"R_0603","resistance_ohm":10000}'),
  (1, 25,  6, 'R15-R20',                     FALSE, '{"footprint_id":"R_0603","resistance_ohm":100}'),
  (1, 26,  2, 'L1-L2',                       FALSE, '{"footprint_id":"L_6045","inductance_uh":10}'),
  (1, 27,  2, 'J1-J2',                       FALSE, '{"footprint_id":"MOLEX_43045_4P"}'),
  (1, 28,  2, 'D2-D3',                       FALSE, '{"footprint_id":"DO214AC_SMA","min_vrwm_v":33}'),
  (1, 30,  4, 'R21-R24',                     FALSE, '{"footprint_id":"R_0603","resistance_ohm":4700}');

-- IG-500 (product 2)
INSERT INTO erp.bom (product_id, component_id, qty_per_unit, reference_designators, is_critical, design_constraints) VALUES
  (2, 16,  1, 'U1',  TRUE,  '{"footprint_id":"ESP32_WROOM_38P","rail_voltage_v":3.3}'),
  (2, 17,  1, 'U2',  TRUE,  '{"footprint_id":"QFN24_4X4_P050","rail_voltage_v":3.3,"interface":"RMII","ambient_temp_min_c":0,"ambient_temp_max_c":70}'),
  (2, 14,  1, 'U3',  FALSE, '{"footprint_id":"SOIC8_208MIL","min_density_mbit":128,"rail_voltage_v":3.3}'),
  (2, 10,  1, 'U4',  FALSE, '{"footprint_id":"SOT223_4L","vout_v":3.3,"min_iout_a":0.8,"ambient_temp_min_c":0,"ambient_temp_max_c":70}'),
  (2,  9,  1, 'U5',  FALSE, '{"footprint_id":"SOIC8_PWPAD"}'),
  (2, 19,  2, 'Y1-Y2', FALSE, '{"footprint_id":"SMD3225_4P","freq_mhz":25.0}'),
  (2, 20,  2, 'D1-D2', FALSE, '{"footprint_id":"SOT23_6L"}'),
  (2, 21, 18, 'C1-C18', FALSE, '{"footprint_id":"C_0603","capacitance_nf":100,"min_voltage_v":50,"dielectric":"X7R"}'),
  (2, 23,  5, 'C19-C23', FALSE, '{"footprint_id":"C_0805","capacitance_nf":10000,"min_voltage_v":25}'),
  (2, 24,  8, 'R1-R8',  FALSE, '{"footprint_id":"R_0603","resistance_ohm":10000}'),
  (2, 25,  4, 'R9-R12', FALSE, '{"footprint_id":"R_0603","resistance_ohm":100}'),
  (2, 27,  2, 'J1-J2',  FALSE, '{"footprint_id":"MOLEX_43045_4P"}'),
  (2, 30,  2, 'R13-R14', FALSE, '{"footprint_id":"R_0603","resistance_ohm":4700}');

-- PI-750 (product 3)
INSERT INTO erp.bom (product_id, component_id, qty_per_unit, reference_designators, is_critical, design_constraints) VALUES
  (3,  4,  1, 'U1',  TRUE,
   '{"footprint_id":"LQFP64_10X10_P050","pinout_family":"STM32F4_R64","rail_voltage_v":3.3,"ambient_temp_min_c":-20,"ambient_temp_max_c":85,"min_flash_kb":512,"min_ram_kb":128,"min_io_count":48,"min_freq_mhz":120,"required_interfaces":["USART","SPI","CAN","ADC12"]}'),
  (3,  8,  8, 'Q1-Q8',   TRUE,  '{"footprint_id":"TO220AB_3L","min_vds_v":80,"min_id_a":120}'),
  (3,  9,  2, 'U2-U3',   FALSE, '{"footprint_id":"SOIC8_PWPAD"}'),
  (3, 10,  1, 'U4',      FALSE, '{"footprint_id":"SOT223_4L","vout_v":3.3,"min_iout_a":0.8}'),
  (3, 12,  1, 'U5',      TRUE,  '{"footprint_id":"SOIC8_150MIL","rail_voltage_v":3.3,"min_data_rate_mbps":1.0}'),
  (3, 19,  1, 'Y1',      FALSE, '{"footprint_id":"SMD3225_4P","freq_mhz":25.0}'),
  (3, 21, 24, 'C1-C24',  FALSE, '{"footprint_id":"C_0603","capacitance_nf":100,"min_voltage_v":50,"dielectric":"X7R"}'),
  (3, 23, 10, 'C25-C34', FALSE, '{"footprint_id":"C_0805","capacitance_nf":10000,"min_voltage_v":25}'),
  (3, 24, 12, 'R1-R12',  FALSE, '{"footprint_id":"R_0603","resistance_ohm":10000}'),
  (3, 26,  3, 'L1-L3',   FALSE, '{"footprint_id":"L_6045","inductance_uh":10}'),
  (3, 27,  3, 'J1-J3',   FALSE, '{"footprint_id":"MOLEX_43045_4P"}'),
  (3, 28,  4, 'D1-D4',   FALSE, '{"footprint_id":"DO214AC_SMA","min_vrwm_v":33}');

-- SD-220 (product 4) -- also uses the STM32F407VGT6, with a LOOSER design spec
-- than MC-3000. Same part, different requirement: this is why compatibility must
-- be judged per design, not per part.
INSERT INTO erp.bom (product_id, component_id, qty_per_unit, reference_designators, is_critical, design_constraints) VALUES
  (4,  1,  1, 'U1', TRUE,
   '{"footprint_id":"LQFP100_14X14_P050","pinout_family":"STM32F4_V100","rail_voltage_v":3.3,"ambient_temp_min_c":-20,"ambient_temp_max_c":70,"min_flash_kb":512,"min_ram_kb":128,"min_io_count":70,"min_freq_mhz":120,"required_interfaces":["USART","SPI","I2C","CAN","ADC12"]}'),
  (4,  7,  1, 'U2', TRUE,  '{"footprint_id":"HTSSOP56_PWP","ambient_temp_min_c":-20,"ambient_temp_max_c":70}'),
  (4,  8,  4, 'Q1-Q4',  TRUE,  '{"footprint_id":"TO220AB_3L","min_vds_v":80,"min_id_a":100}'),
  (4,  9,  1, 'U3',     FALSE, '{"footprint_id":"SOIC8_PWPAD"}'),
  (4, 12,  1, 'U4',     TRUE,  '{"footprint_id":"SOIC8_150MIL","rail_voltage_v":3.3,"min_data_rate_mbps":1.0}'),
  (4, 14,  1, 'U5',     FALSE, '{"footprint_id":"SOIC8_208MIL","min_density_mbit":128,"rail_voltage_v":3.3}'),
  (4, 19,  1, 'Y1',     FALSE, '{"footprint_id":"SMD3225_4P","freq_mhz":25.0}'),
  (4, 21, 22, 'C1-C22', FALSE, '{"footprint_id":"C_0603","capacitance_nf":100,"min_voltage_v":50,"dielectric":"X7R"}'),
  (4, 23,  6, 'C23-C28', FALSE, '{"footprint_id":"C_0805","capacitance_nf":10000,"min_voltage_v":25}'),
  (4, 24, 10, 'R1-R10', FALSE, '{"footprint_id":"R_0603","resistance_ohm":10000}'),
  (4, 26,  2, 'L1-L2',  FALSE, '{"footprint_id":"L_6045","inductance_uh":10}'),
  (4, 27,  1, 'J1',     FALSE, '{"footprint_id":"MOLEX_43045_4P"}');

-- -------------------------------------------------------- sourcing (MCUs)
-- These rows are hand-set because the demo arithmetic depends on them.
-- Note the shape of the problem: the incumbent part (STM32F407VGT6) is only
-- available in VOLUME from the two Chinese suppliers. The Western distributors
-- hold single-digit-hundreds. That is exactly why an alternative is needed.
INSERT INTO erp.supplier_components (supplier_id, component_id, supplier_part_no, unit_price, lead_time_days, moq, stock_available) VALUES
  -- STM32F407VGT6 (incumbent)
  (1,  1, 'RY-STM32F407VGT6',  9.4000, 21, 500, 12000),
  (8,  1, 'FLT-407VGT6',       9.1000, 25, 1000, 6000),
  (4,  1, '497-11761-ND',      12.4000, 7,   1,   800),
  (5,  1, '511-STM32F407VGT6', 12.1000, 10,  1,   450),
  (6,  1, 'STM32F407VGT6-ND',  12.8000, 5,   1,   300),
  -- STM32F429VGT6 (primary alternative)
  (4,  2, '497-14606-ND',      11.2000, 7,   1,  2000),
  (5,  2, '511-STM32F429VGT6', 10.8500, 15,  1,  5000),
  (6,  2, 'STM32F429VGT6-AR',  11.6000, 5,   1,  8000),
  (7,  2, 'AVT-F429VGT6',      11.0500, 12, 100, 3000),
  (10, 2, 'RUT-F429VGT6',      11.9000, 9,  100, 1500),
  -- STM32F429ZIT6
  (4,  3, '497-14609-ND',      13.1000, 7,   1,  1800),
  (5,  3, '511-STM32F429ZIT6', 12.7000, 12,  1,  2400),
  -- STM32F405RGT6
  (4,  4, '497-11767-ND',       9.6000, 7,   1,  3000),
  (5,  4, '511-STM32F405RGT6',  9.3000, 11,  1,  4000),
  (1,  4, 'RY-STM32F405RGT6',   7.8000, 21, 500, 9000),
  -- GD32F407VGT6 (technically valid, but sourced only from the affected region)
  (1,  5, 'RY-GD32F407VGT6',    6.2000, 18, 500, 20000),
  (8,  5, 'FLT-GD407VGT6',      5.9500, 22, 1000, 15000),
  -- STM32F407VGT7 (industrial temp grade, low stock, premium price)
  (4,  6, '497-15102-ND',      13.9000, 14,  1,   600),
  (6,  6, 'STM32F407VGT7-AR',  13.4000, 11,  1,  1200);

-- ------------------------------------------------ inventory (critical part)
-- 7,700 on hand - 1,200 reserved - 500 safety = 6,000 usable for this horizon.
INSERT INTO erp.inventory (component_id, warehouse_id, quantity, reserved_quantity, safety_stock) VALUES
  (1, 1, 7700, 1200, 500);

-- ----------------------------------------------------------- purchase orders
INSERT INTO erp.purchase_orders (id, po_number, supplier_id, status, order_date, expected_date, incoterm, ship_from_country) VALUES
  (1, 'PO-2026-0142', 1, 'RECEIVED', DATE '2026-06-10', DATE '2026-07-05', 'FOB', 'China'),
  (2, 'PO-2026-0154', 4, 'RECEIVED', DATE '2026-07-02', DATE '2026-07-11', 'DAP', 'United States'),
  (3, 'PO-2026-0187', 1, 'OPEN',     DATE '2026-08-12', DATE '2026-09-28', 'FOB', 'China'),
  (4, 'PO-2026-0191', 6, 'OPEN',     DATE '2026-08-20', DATE '2026-09-15', 'DAP', 'United States'),
  (5, 'PO-2026-0195', 2, 'OPEN',     DATE '2026-08-25', DATE '2026-09-22', 'FOB', 'Taiwan'),
  (6, 'PO-2026-0198', 5, 'OPEN',     DATE '2026-08-28', DATE '2026-09-30', 'DAP', 'United States');

INSERT INTO erp.purchase_order_items (po_id, component_id, quantity, received_qty, unit_price) VALUES
  (1, 1, 5000, 5000,  9.4000),   -- previous STM32F407 buy, fully received
  (2, 14, 3000, 3000, 1.8500),
  (3, 1, 4000, 0,     9.4000),   -- <<< the 4,000 units the disruption puts at risk
  (4, 7, 1500, 0,     4.8500),
  (5, 8, 12000, 0,    2.3500),
  (6, 16, 2500, 0,    3.1000);

-- --------------------------------------------------------- external events
-- Synthetic demo feed. Nothing here is a real published report; is_synthetic is
-- TRUE on every row so the UI can label it. "extracted" is intentionally empty:
-- populating it is the Intelligence Agent job.
--
-- Events 1 and 4 are genuinely relevant to this company. The rest are NOISE and
-- exist so the agent has to discriminate rather than react to everything.
INSERT INTO platform.external_events (id, external_id, source, source_type, is_synthetic, headline, body, url, published_at) VALUES
  (1, 'EVT-2026-09-02-001', 'SYNTHETIC_DEMO_FEED', 'GOVERNMENT', TRUE,
   'New export licence requirement announced for microcontroller and logic IC shipments originating in China',
   'A notice published on 2 September 2026 introduces a licensing requirement for the export of microcontrollers and general-purpose logic integrated circuits (HS heading 8542) manufactured in or re-exported from China. Licences will be required for all shipments departing on or after 20 September 2026. Industry bodies expect an initial processing backlog of four to eight weeks and warn that shipments already booked but not yet cleared may be held. Distributors in Shenzhen and Xiamen are reported to be reviewing outstanding order books.',
   'https://example.invalid/demo-feed/evt-2026-09-02-001', TIMESTAMPTZ '2026-09-02 09:15:00+00'),

  (2, 'EVT-2026-09-01-014', 'SYNTHETIC_DEMO_FEED', 'NEWS', TRUE,
   'Typhoon forces suspension of container operations at Kaohsiung port',
   'Container handling at Kaohsiung was suspended for 36 hours as a typhoon passed the southern coast of Taiwan. Terminal operators expect a backlog of three to five days once operations resume. No damage to terminal infrastructure has been reported.',
   'https://example.invalid/demo-feed/evt-2026-09-01-014', TIMESTAMPTZ '2026-09-01 22:40:00+00'),

  (3, 'EVT-2026-08-29-007', 'SYNTHETIC_DEMO_FEED', 'NEWS', TRUE,
   'Copper closes 14 percent higher on the quarter as mine output disappoints',
   'Copper prices ended the quarter up 14 percent, driven by lower than expected output at two large South American mines. Analysts expect the increase to feed through to wiring, connector and magnetics costs over the next two quarters.',
   'https://example.invalid/demo-feed/evt-2026-08-29-007', TIMESTAMPTZ '2026-08-29 16:05:00+00'),

  (4, 'EVT-2026-08-30-002', 'SYNTHETIC_DEMO_FEED', 'NEWS', TRUE,
   'Fire halts production at a multilayer ceramic capacitor plant in Fukui prefecture',
   'A fire on 29 August has halted production at a multilayer ceramic capacitor facility in Fukui prefecture, Japan. The operator has not given a restart date. The site is understood to produce small-case-size X5R and X7R parts. Buyers have been advised to expect allocation on 0603 and 0805 lines.',
   'https://example.invalid/demo-feed/evt-2026-08-30-002', TIMESTAMPTZ '2026-08-30 11:20:00+00'),

  (5, 'EVT-2026-08-27-019', 'SYNTHETIC_DEMO_FEED', 'REGULATORY', TRUE,
   'Consultation opens on revised tariff classification for imported power semiconductor modules',
   'A consultation has opened on reclassifying certain imported power semiconductor modules, which would change the applicable duty rate. The consultation runs for 90 days and any change would take effect no earlier than the following fiscal year.',
   'https://example.invalid/demo-feed/evt-2026-08-27-019', TIMESTAMPTZ '2026-08-27 08:00:00+00'),

  (6, 'EVT-2026-08-31-011', 'SYNTHETIC_DEMO_FEED', 'NEWS', TRUE,
   'Distributors report 20 week lead times returning on automotive grade microcontrollers',
   'Several distributors report that quoted lead times on automotive qualified microcontrollers have moved back towards 20 weeks after two quarters of improvement, citing wafer allocation being shifted to higher margin product lines.',
   'https://example.invalid/demo-feed/evt-2026-08-31-011', TIMESTAMPTZ '2026-08-31 07:30:00+00'),

  (7, 'EVT-2026-08-20-033', 'SYNTHETIC_DEMO_FEED', 'NEWS', TRUE,
   'Global smartphone shipments slip 3 percent in the second quarter',
   'Smartphone shipments fell 3 percent year on year in the second quarter, with the decline concentrated in entry level models. Vendors expect a flat second half.',
   'https://example.invalid/demo-feed/evt-2026-08-20-033', TIMESTAMPTZ '2026-08-20 13:10:00+00');
